### ISSUE TITLE
имена в table.hpp

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp#10]
При сборке проекта получаю ошибку использования имени функции `CreateWindow` и `RGB`. В закрытых issues нашел [предложенное решение](https://github.com/elelel/qluacpp/issues/6) . Убрал из проекта все файлы `#include <window.h>` - не помогло. Ест предложение изменить имена функций в библиотеке qluacpp, чтобы они не совпадали с именами в макросе. 

```

contrib/qluacpp/src/qlua/api/table.hpp:33:30: error: expected ';' at end of member declaration
                              CreateWindow,
                              ^
F:/Imp/Plug-ins DLL/Qt_project/qluacpp_tutorial/contrib/qluacpp/src/qlua/api/macros.h:12:15: note: in definition of macro 'QLUACPP_DETAIL_API_FUNCTION4'
   RETURN_TYPE NAME(ARG1_TYPE ARG1) const {                      \
               ^
F:/Imp/Plug-ins DLL/Qt_project/qluacpp_tutorial/contrib/qluacpp/src/qlua/api/macros.h:12:42: error: expected unqualified-id before '{' token
   RETURN_TYPE NAME(ARG1_TYPE ARG1) const {                      \
```
Работае так
```
#undef CreateWindow
#undef RGB
```
но для чистой библиотеки может стоит изменит имена этих двух функций?

**Comment by elelel** [comment]
Тогда оно не будет совпадать с родной документацией к API Qlua, а у меня цель, чтоб объект qlua::api максимально точно повторял информацию из qlua.chm. То есть, чтоб программист мог создать начальный проект, а далее идти практически по документации QLua. Все надстройки и переделки я планирую поместить в qlua::extended_api (например нормальный объект таблиц в C++ стиле и т.п.). То что вам помогает #undef говорит о том, что в этом файле где-то инклюдится windows.h (например, через stdafx.h). Пользователю нужно всего-лишь учитывать, какие файлы заголовков он использует в своем исходнике и не использовать конфликтующие. К сожалению, в стародавние времена, в Microsoft считали, что их компилятор будет единственным и что весь глобальный неймспейс принадлежит им, поэтому бездумно использовали C макросы для создания переключателя между ANSI и Widechar версиями функций (как с CreateWindow) или просто для "удобства" (как с RGB, min/max и тп). Не подключать windows заголовки в файле исходника, если он использует крупную мультиплатформенную библиотеку, или делать дефы, андефы и редефы - теперь частая практика.

**Comment by QApplication** [comment]
Предлагаю добавить 
```cpp
#undef CreateWindow
#undef RGB
```
in file `table.hpp`
чтобы явно исключить получающееся противоречие в пространстве имен.

**Comment by elelel** [comment]
Здесь это не будет иметь смысла, потому что это имена из публичного интерфейса. Пользователь подключил две библиотеки: qluacpp и windows.h. Дальше он написал CreateWindow в своей программе, как он сам должен понимать, к какому имени он обратился?
