### ISSUE TITLE
CreateDataSource

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp#11]
При обращении к методу `ds_->T(i)` где ` std::unique_ptr<qlua::data_source> ds_` происходит падение клиента, ни каких исключений не выбрасывается. При этом, при обращении к методам `ds_->O(i);` и др. все работает стабильно.
Счетчик `i` не доходит до своего верхнего значения в цикле.

![cds1 bmp](https://user-images.githubusercontent.com/31853792/33517498-5d5bc818-d796-11e7-8421-9d9cbee36565.jpg)
![cds2 bmp](https://user-images.githubusercontent.com/31853792/33517501-685991fa-d796-11e7-84ae-32167144c72b.jpg)

**Comment by elelel** [comment]
Исправил,  e680353 , на моих тестах работает. Проверьте, пожалуйста, у себя.

**Comment by QApplication** [comment]
у меня работает стабильно

**Comment by elelel** [comment]
Спасибо, закрываю
