### ISSUE TITLE
callback OnTransReply 

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp#14]
```cpp
err: callback_OnTransReply _ Luacpp entity get: typecheck failed (Lua type at stack index -1 is nil; content as string: <Oops, got null from Lua when tried to get actual content as string>)
```

**Comment by QApplication** [comment]
ошибка в типе поля `exchange_code`

**Comment by elelel** [comment]
По документации он может содержать nil. Такие поля я планирую сделать std::optional<...>, будет частью перевода на C++17

**Comment by elelel** [comment]
Должно быть исправлено ae7901b652e1c3520e8d1a4a474ce6b2bfdcc04a
Если нет, переоткройте issue
