### ISSUE TITLE
Добрый день. Помогите пожалуйста.

### ISSUE THREAD

**Issue by AlexLan73** [elelel/qluacpp#15]
Добрый день.
Вижу проделана огромная работа, "снимаю шляпу перед Вами". 
К сожалению не удается запустить((
выдает ошибку
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.13.26128\include\optional(15): fatal error C1189: #error:  class template optional is only available with C++17.
  ninja: build stopped: subcommand failed.
К сожалению, я не знаком с cmake  и nmake (((
Запускаю прямо из среды VS2017 но ругается 
Пожалуйста помогите решить проблему. 
Я, не профессиональный программист - это мое хобби.
С уважением, Александр

**Comment by elelel** [comment]
Здравствуйте,
Последнии версии Qluacpp требуют поддержку стандарта C++17. В компиляторах от Microsoft она включается флагом /std:c++17 если у вас свежая версия студии 2017 или флагом /std:c++latest, если не свежая. Если вы работаете через IDE, то указать это можно в свойствах проекта в  Project/Properties/C++/Language

**Comment by AlexLan73** [comment]
Спасибо за ответ)
Как мне к Вам обращаться,? Как Вас   зовут?
Версия 17  "Свежая"))) русская 
извините ((( я не могу найти где это ((  подскажите пожалуйста (прицепил бы картинку но не знаю как ()
"Если вы работаете через IDE, то указать это можно в свойствах проекта в Project/Properties/C++/Language"

**Comment by AlexLan73** [comment]
![24-03-2018 19-46-12](https://user-images.githubusercontent.com/37739293/37865969-59aa7e62-2f9d-11e8-97fc-f4a0a59934fe.png)

**Comment by elelel** [comment]
Меню Проект - Свойства(?) - C++ - Язык(?)

**Comment by AlexLan73** [comment]
Когда обычный проект так оно и есть. 
Но у Вас Cmake и  пот этого "Проект - Свойства(?) - C++ - Язык(?)" там нет
А где? не  знаю убил весь день ((
Наверно в пустую
Может у Вам есть Ваш проект без всяких make ((
что бы просто, по людски скопировать, собрать и пользоваться 
Вспоминая Вас добрым словом)))

**Comment by elelel** [comment]
У меня CMake - где? У меня, возможно, CMake (в примерах), но у меня и IDE студии нет, скриншоты которой вы прислали. Что вы пытаетесь запустить?

**Comment by AlexLan73** [comment]
через git клонировал qluacpp
при запуске VS2017, программа распознает что нужно собирать  через make,
 и выдает другое меню в котором нет настройки компилятора или ....
в меню проект там вот что 
![24-03-2018 20-20-23](https://user-images.githubusercontent.com/37739293/37866265-dfbd6e70-2fa1-11e8-9900-420c04dd3b00.png)

**Comment by AlexLan73** [comment]
Я посмотрел на Ваш код))) это код профессионала -красивый))
Мне есть чему учиться но проблема с запуском(((

**Comment by elelel** [comment]
В git репозитарии qluacpp нет проекта, который нужно было бы компилировать, чтоб подключить библиотеку. Нужно создать свой проект в среде по своему вкусу, написать код своего проекта, положить внутрь этого проекта библиотеку (то, что вы склонировали), и по мере надобности из кода своего проекта обращаться к библиотеке. Библиотека никак не зависит от конкретной среды и не требует отдельной компиляции. При этом свой проект следует компилировать с поддержкой стандарта С++17. Как указать в проекте в среде IDE Visual Studio стандарт языка, я нашел поисковиком на английском и привел вам, как и свой вольный перевод.

**Comment by AlexLan73** [comment]
Ладно по пробую по другому.
Жалко что  целый день потерял 
**на этом "Создание CMake проекта"**
**на этом  "Сборка проекта
В любом удобном месте, не внутри директории с репозитарием проекта, мы должны создать директории, в которые будет сгенерирован при помощи CMake проект под нужную нам среду.

В меню Start Windows ищем Command Prompt for VS2017. При выборе следует помнить, что мы компилируем 32-битный проект. Поэтому, если компиляция происходит на 64-битном Windows, следует выбирать x64_x86 Cross Tools Command Prompt.**
**Компиляция проекта при помощи NMake"**
А выясняется, что все это .... 

"Нужно создать свой проект в среде по своему вкусу, написать код своего проекта, положить внутрь этого проекта библиотеку "

А Вы пробовали просто скопировать Ваш пример? По кнопке в zip фале.
Там пустые каталоги .
Красиво написано (код), не плохое описание - но получается бесталанное просто не о чем((????
+ не полный код при копировании пустые каталоги .

Простите меня старого но это халтура.
Извините меня за мою резкость но жалко потерянного дня
Вот простое описание 
https://quikluacsharp.ru/qlua-c-cpp-csharp/obmen-dannymi-mezhdu-dll-c-c-i-prilozheniem-c/
когда я его прочитал статью в 15 году **за час** написал программу  связал N quik + привод + amibroker
На Вас я наткнулся на форуме Quik - проблема многозадачность - подумал парень голова!! 
и вот такой облом

**Comment by elelel** [comment]
Каждый пример я создавал пошагово и записывал, естественно "пробовал". Примеры из репозитария qluacpp-tutorial не касаются вопроса создания проекта в IDE Visual Studio и основаны все на CMake. Вы задали вопрос по IDE Visual Studio, на который я ответил по мере своих знаний, не работаю с нею и в ближайшее время не планирую. Чтобы научиться создавать проекты в IDE Visual Studio, следует обратиться к посвященному этому источнику, например MSDN. "Простота" описания - есть субъективная величина, зависящая не только от самого описания, но и от способности пытающегося понять к пониманию. Вполне естественно, что одни источники подходят одним людям больше, другие - меньше.
