### ISSUE TITLE
std::optional<T> для get<Name>Ex(args...)

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp#19]
Добрый день.
Прошу добавить возвращаемые функциями типы данных через `std::optional`, так как они могут возвращать nil в случае ошибки, например входных параметров (QUIK 8.0.4.4).

Функции возвращают таблицу Lua с параметрами таблицы
```
q.getMoneyEx(args...) //«Позиции по деньгам»
q.getDepoEx(args...) //«Позиции по инструментам»
q.getFuturesLimit(args...) //«Ограничения по клиентским счетам»
q.getFuturesHolding(args...)  //«Позиции по клиентским счетам»
```
В текущей версии библиотеки `QLUACPP` выдается `Exception at 0x7ffe90d3a388, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at qluacpp\contrib\luacpp\src\entity.hpp:63`

**Comment by elelel** [comment]
"Таблицы", которые объявлены как LUACPP_STATIC_TABLE, являются accessor-объектами к данным терминала (Lua-таблицам, которые на самом деле таблицы). Объект всегда будет существовать, даже если таблица nil, поэтому его нет смысла оборачивать в optional. Это нужно, например, когда программист хочет создать новую таблицу в Lua - будет момент, когда объект уже есть, а таблицы еще нет, и это нормально.
Данные, которые находятся внутри lua-таблиц, тут тоже неправильно оборачивать в optional, потому что это меняет семантику: одно дело, когда могут отсутствовать данные в этих полях (и тогда мы применяем optional для их возврата), другое дело, когда нет самой таблицы (и тогда мы не можем использовать optional для возврата полей). В описанном вами случае следует проверять, находится ли на стеке таблица. Для удобства я добавил функцию is_nil() в сам макрос объявления таблиц. Также, если случается exception, лучше его ловить и писать информацию о нем сюда, qluacpp пишет какой тип данных ожидает, какой находится на самом деле. Так быстрее диагностировать. Если информации нет, то это тоже ошибка, которую следует исправлять в библиотеке.

**Comment by QApplication** [comment]
Проверил, работает. Спасибо за быстрый ответ.
