### ISSUE TITLE
Как вызвать getItem?

### ISSUE THREAD

**Issue by mmonk1980** [elelel/qluacpp#2]
тут пишет ошибку:

auto item_t = q.getItem("all_trades", 0).price;

**Comment by mmonk1980** [comment]
auto it = q.getItem<>("all_trades", 0);

выдает такую ошибку:

'qlua::api::getItem': no matching overloaded function found
'item_t qlua::api::getItem(const char *,const int) const': could not deduce template argument for 'item_t'

видимо функция не реализована.

**Comment by elelel** [comment]
Функция реализована, укажите получаемый тип данных, иначе его ваш компилятор не может вычислить.

**Comment by mmonk1980** [comment]
А как правильно? Можете переписать эту строку? (getItem чтобы вoзращала price)

auto item_t = q.getItem("all_trades", 0).price;

**Comment by elelel** [comment]
auto it = g.getItem<ТИП_ДАННЫХ>("all_trades", 0);

**Comment by mmonk1980** [comment]
price где?

**Comment by mmonk1980** [comment]
all_trades много переменных где-то 50 штук.

**Comment by mmonk1980** [comment]
нужно или таблицу вызывать и с ней работать или еще как?

**Comment by elelel** [comment]
getItem возвращает строку таблицы, чтоб ее вернуть, надо знать тип возвращаемой записи. Не компилировалось поэтому.
price - очевидно, это что-то внутри этой записи, и уже второй вопрос. Если в той структуре есть такое поле, то значит .price.
Последние ваши две реплики я не понял.

**Comment by mmonk1980** [comment]
all_trades[9168]{
-- Table: {1}
{
   ["repoterm"]=0,
   ["price"]=55.64,
   ["trade_num"]=1757627137,
   ["yield"]=0,
   ["value"]=688325.88,
   ["qty"]=22,
   ["reporate"]=0,
   ["class_code"]="SPBFUT",
   ["repovalue"]=0,
   ["exchange_code"]="",
   ["accruedint"]=0,
   ["tradenum"]=1757627137,
   ["flags"]=1,
   ["datetime"]={2},
   ["sec_code"]="BRK7",
   ["seccode"]="BRK7",
   ["settlecode"]="",
   ["period"]=0,
   ["repo2value"]=0,
   ["open_interest"]=636304,
}

**Comment by mmonk1980** [comment]
как узнать price?

**Comment by mmonk1980** [comment]
в lua это делается легко:

t = getItem("all_trades", 743871).price

**Comment by mmonk1980** [comment]
как c++ не вашей либой я не знаю.

**Comment by mmonk1980** [comment]
мне кажется это не реализовано.

**Comment by mmonk1980** [comment]
Если хотим вывести tradenum такой код: t = getItem("all_trades", 743871).tradenum

**Comment by elelel** [comment]
> мне кажется это не реализовано.

 Реализовано [здесь](https://github.com/elelel/qluacpp/blob/master/src/api/structs/alltrade.hpp)

**Comment by mmonk1980** [comment]
Вот данные не достать.

**Comment by mmonk1980** [comment]
t = getItem("all_trades", 743871).tradenum
t2 = getItem("all_trades", 743871).price

как будет с С++ и вашей либой?

**Comment by elelel** [comment]
```c++
  auto it = q.getItem<qlua::alltrade>("all_trades", 0);
  q.message("Price " + std::to_string(it.price));
``` 
Этот вопрос не касается библиотеки, а обучение пользователей языку С++ не входило в мои намерения.

**Comment by mmonk1980** [comment]
2 дня, а о вас этой строки добивался! Все работает! Как вычистили <ТИП_ДАННЫХ> это был qlua::alltrade?

**Comment by elelel** [comment]
Не понял вопрос про "вычистили".

**Comment by mmonk1980** [comment]
вычислить

**Comment by mmonk1980** [comment]
Чтобы я вам с этими вопросами не приставал.

**Comment by elelel** [comment]
getItem должен знать, какой тип данных от него требуют. Программист, вызывая getItem должен знать, что он хочет от него получить. Чтобы узнать, какие типы может возвращать getItem, можно посмотреть руководство QLUA от Arqa (названия обычно совпадают с их названиями) или смотреть директорию structs от библиотеки, где находятся файлы структур, как я указал выше.
Если я понял вопрос.

**Comment by mmonk1980** [comment]
И кстати почему библиотека написана C++ 11, он же тормозной?

**Comment by mmonk1980** [comment]
если C++ лучше C то будет 2 раза быстрей, а здесь это надо.
