### ISSUE TITLE
несколько SetUpdateCallback - вызывается только последний callback

### ISSUE THREAD

**Issue by lvnvlad** [elelel/qluacpp#21]
Создал несколько data_source с помощью CreateDataSource, для каждого назначил callback функцию с помощью SetUpdateCallback. В результате вызывается только последняя установленная callback функция, в которую приходят данных от всех data_source.

**Comment by elelel** [comment]
Добавил поддержку нескольких датасорс/коллбеков в 19965b618cd04334e7c7afabce542d39ac65eb7c, но протестировать пока у меня возможности нет.

**Comment by elelel** [comment]
Вообще оно должно было работать и со старым вариантом, покажите, пожалуйста код, как создаете функции колбека.

**Comment by lvnvlad** [comment]
unsigned int interval_ = q_->constant<unsigned int>("INTERVAL_M1");
ds = std::unique_ptr<qlua::data_source>(new ::qlua::data_source(q_->CreateDataSource("INDX", "MOEX10", interval_)));
        if (!SetUpdateCallback("OnCandleMoex10")
        {
            std::cout << "ERROR: Failed to set update callback on datasource: false returned";
        }
ds = std::unique_ptr<qlua::data_source>(new ::qlua::data_source(q_->CreateDataSource("INDX", "MOEX", interval_)));
        if (!SetUpdateCallback("OnCandleMoex")
        {
            std::cout << "ERROR: Failed to set update callback on datasource: false returned";
        }

**Comment by elelel** [comment]
Спасибо, нашел ошибку в luacpp и исправил: https://github.com/elelel/luacpp/commit/749dbd8598fddb1a814718e08fce6fce38eca356
