### ISSUE TITLE
limit_kind field

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp#25]
Добрый день.
Предлагаю заменить тип поля **limit_kind** на **int**
![image](https://user-images.githubusercontent.com/31853792/66434116-a7dc0c00-e9d6-11e9-9583-0b23665e250a.png)
Отрицательные значения реально присутствуют в таблицах **money_limits**, **money_limit_delete**, **depo_limits**, **depo_limit_delete** если в торговую сессию совершались операции на рынке. При этом, в таблицах quik такие строки не отображаются, но при запросе теблиц, например через getItem(...) такая строка присутствует.

**Comment by elelel** [comment]
Поддерживаю, сделал в 1e2d2e59edb5f47814b6e1daf978446f0352a6f7
