### ISSUE TITLE
callback OnTrade Exception

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp#26]
Добрый день.
При вызове callback OnTrade кидается исключение 
`Exception at 0x7ff82b7ca388, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at ...\contrib\qluacpp\contrib\luacpp\src\entity.hpp:63`

`EXCEPTION:  Luacpp entity get: typecheck failed (Lua type at stack index -1 is nil; content as string: <Oops, got null from Lua when tried to get actual content as string>)
`

Предположение: _в связи с переходом на 19-значное число ордеров и заявок quik._
![image](https://user-images.githubusercontent.com/31853792/74532621-7e7f3f80-4ee4-11ea-8c0c-bac45bfd58cf.png)

текущий тип в qluacpp - uint
Общее описание проблемы привел в [issues](https://github.com/elelel/qluacpp/issues/27)

**Comment by elelel** [comment]
Дубликат #27
