### ISSUE TITLE
Изменение нумерации заявок и сделок в Spectra 6.3

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp#27]
Добрый день.
Прошу Вас внести изменения в библиотеку [в связи с переходом Spectra 6.3 с 14-значного на 19-значные номера заявок и сделок](https://www.moex.com/n26101/?nt=107). Ссылка на [ветку quik форума](https://forum.quik.ru/forum10/topic4909/). Проблему частично описал в [issues](https://github.com/elelel/qluacpp/issues/26).

Изменения предположительно [касаются](https://github.com/elelel/qluacpp/blob/master/src/qlua/structs/standalone.hpp):
1. table **orders** field **order_num**
2. table **trades**  field **trade_num**
3. table **trades**  field **order_num**
4. table **stop_orders**  field **order_num**
5. table **stop_orders**  field **co_order_num**
6. table **neg_trades**  field **order_num**
7. table **trans_reply**  field **order_num**
8. table **all_trades**  field **trade_num**
9. table **stop_orders**  field **alltrade_num**
10. table **neg_trades**  field **trade_num**

Пример значения полей callback alltrade, полученные через qluacpp quik
![image](https://user-images.githubusercontent.com/31853792/74533969-a6bc6d80-4ee7-11ea-985d-9e0739ae6b8f.png)
при этом аналогичные значения в quik для приведенной выше сделки
![image](https://user-images.githubusercontent.com/31853792/74534271-36621c00-4ee8-11ea-8634-58bda7bada53.png)

QUIK 8.3.2.4
Библиотеки (на сколько я понял используется lua5.1 (на lua5.3 quik не перешел))
![image](https://user-images.githubusercontent.com/31853792/74535125-0451b980-4eea-11ea-8d28-55a06df35413.png)

![image](https://user-images.githubusercontent.com/31853792/74535083-f3a14380-4ee9-11ea-8854-e4ff5ac6d875.png)

**Comment by elelel** [comment]
Номер сделок (trade_num) обновил в 7e222c60400be66207d636a40f41aa3b00520040
Номер заявок (order_num) не обновлял, у вас есть возможность подтвердить, что они тоже не работают и стали 19-значными? Я к сожалению, не могу проверить, FORTS есть только на продакшн терминалах, работу с ним сейчас не веду, а Quik Junior (demo-доступ от Arqa) до сих пор транслирует записи со старыми номерами сделок и в вопросе заявок на него опираться так же нельзя.

**Comment by QApplication** [comment]
На moex   ([#1#](https://www.moex.com/n26015) [#2#](https://www.moex.com/n26052) [#3#](https://www.moex.com/n26101/?nt=107) ) говорится об изменении нумерации заявок и сделок

![image](https://user-images.githubusercontent.com/31853792/74642528-04d79380-5128-11ea-8e2f-6ec28521a857.png)

**Comment by QApplication** [comment]
Каким Вы сейчас пользуетесь терминалом на moex?

**Comment by elelel** [comment]
В этих сообщениях идет только о срочном рынке (Spectra). На срочном рынке в демо-терминале Квика идет проигрыш старых записанных событий, то есть со старыми номерами сделок, поэтому там я не могу проверить какие поля изменились, а какие нет. Являются ли все поля, называемые orders в QLua полями, куда транслируются номера сделок со срочного рынка, или часть этих полей осталась Int и их менять не нужно. У меня есть доступ к продакшн терминалам Quik 8  64-битному и 7 32-битному, на которых можно это проверить, исполнив реальные сделки на реальной бирже и посмотреть, какие будут номера в каких таблицах. Но на срочном рынке я заявки не выставляю сделки не исполняю в настоящий момент, и специально исполнить ради проверки у меня тоже возможности нет. Что касается пассивной информации, типа all_trades сделок, их я проверил в 64 и 32 терминалах.

**Comment by QApplication** [comment]
выше я привел таблицу ордеров для срочного рынка с ордером на покупку - нужно посмотреть как при этом работет qluacpp? или нужно сделку совершить?

**Comment by QApplication** [comment]
Проверил работу OnOrder callback на срочном рынке.
При выставлении ордера, а также его снятия, кидается исключение (предположительно на поле **order_num**)
```
Exception at 0x7ffb633aa388, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at contrib\qluacpp\contrib\luacpp\src\entity.hpp:63
PLUGIN:  2020-Feb-17 11:25:22.908 void __cdecl quik::QLua::OnOrder(const struct lua::state &,const struct lua::entity<struct lua::type_policy<class qlua::table::orders> > &) 	 EXCEPTION:  Luacpp entity get: typecheck failed (Lua type at stack index -1 is nil; content as string: <Oops, got null from Lua when tried to get actual content as string>)
```
Также брокер за спамил сообщением
![image](https://user-images.githubusercontent.com/31853792/74681871-565c3e80-5179-11ea-8c84-beb64f899e4d.png)

Думаю можно смело менять все поля ордеров на _string_

**Comment by elelel** [comment]
Давайте действительно сделаем так. Заменю все поля с номерами сделок/заявок на строки. А если у кого-то возникнут проблемы с измененными номерами, уже будем фиксить по месту.

**Comment by QApplication** [comment]
Ок, буду тестить на фонде и срочном рынках. Спасибо за оперативность.

**Comment by elelel** [comment]
Добавил, когда будете тестировать, проверьте, пожалуйста стоп-заявки. Думаю, там используется внутренний номер сервера Quik, и его следует откатить обратно в int.

**Comment by QApplication** [comment]
Проверил стоп-заявку, исключений из-за смены типа данных номера `int `to `string `не кидает.

QUIK:
![image](https://user-images.githubusercontent.com/31853792/74767710-39d50a80-523c-11ea-9bd6-144c4f52f122.png)

QLUACPP:
![image](https://user-images.githubusercontent.com/31853792/74768564-a69cd480-523d-11ea-9144-d472a34b3ff4.png)

**Comment by QApplication** [comment]
Проверил лимитную заявку на FORTS (SPBFUT), иключений не кидает
QUIK:
![image](https://user-images.githubusercontent.com/31853792/74769243-e57f5a00-523e-11ea-8d1f-d552f4a0bd4c.png)
QLUACPP:
![image](https://user-images.githubusercontent.com/31853792/74769360-20818d80-523f-11ea-82f6-683d268cdd9f.png)

**Comment by QApplication** [comment]
alltrade callback работает без иключений
![image](https://user-images.githubusercontent.com/31853792/74770131-802c6880-5240-11ea-854e-b1c43e0175e4.png)

**Comment by QApplication** [comment]
Завтра скину сканы с транзакций

**Comment by elelel** [comment]
> Проверил стоп-заявку, исключений из-за смены типа данных номера `int `to `string `не кидает.
> 
> QUIK:
> ![image](https://user-images.githubusercontent.com/31853792/74767710-39d50a80-523c-11ea-9bd6-144c4f52f122.png)
> 

Судя по скрину, order_num короткий?

**Comment by QApplication** [comment]
да, номер короткий. У меня есть предположение, что арка когда нибудь и эти ордера переведет на 19-значные.
Теоретически можно оставить uint.
