### ISSUE TITLE
flags field in OnOrder and OnStopOrder callbacks

### ISSUE THREAD

**Issue by QApplication** [elelel/qluacpp#29]
Добрый день.
Прошу внести корректировки в поле flag, так как оно не соответствует описанным в qlua.chm.
[скрин ](https://github.com/elelel/qluacpp/issues/27#issuecomment-587680769)1, [скрин2](https://github.com/elelel/qluacpp/issues/27#issuecomment-587664455)

![image](https://user-images.githubusercontent.com/31853792/74771460-0f3a8000-5243-11ea-9621-129301d1215d.png)

**Comment by elelel** [comment]
Что именно не соответствует? Например, скрине2 флаг 26, это 11010:
- заявка не активна
- заявка снята
- заявка на покупку
- лимитированная заявка
- не ожидает активации
Флаг 25, это 11001:
- заявка активна
- заявка не снята и не исполнена
- заявка на покупку
- лимитированная заявка
- не ожидает активации

Вроде бы, соответствует скрину с данными из окна терминала. Если считывать флаг напрямую из Lua скрипта, получаются другие значения?

**Comment by QApplication** [comment]
Таким образом необходимо подбирать состояние битов чтобы получить значение, соответствующее. например, `flags = 25`

**Comment by elelel** [comment]
> Таким образом необходимо подбирать состояние битов чтобы получить значение, соответствующее. например, `flags = 25`

Подбирать ничего не надо, работа с битовыми флагами такая же, как в QLua на Lua. Или как в C/C++ в любом приложении:

if (flags & CONSTANT) { ... };   // CONSTANT - константа со включенным интересующим битом, например 0x800 для бита 11

**Comment by QApplication** [comment]
поправьте если я не правильно понимаю:
поле flags выводит uint значение, полеченное [как](https://docs.microsoft.com/ru-ru/cpp/standard-library/bitset-class?view=vs-2019#to_ullong) по значению полей. обратная операция в классе std::bitset не приведена

**Comment by elelel** [comment]
Да, библиотека не навязывает использование std::bitset. Собственно, std::bitset не так часто используется в C++ для сравнения битов, им неудобно пользоваться для многобитовых масок, например. 
- https://stackoverflow.com/questions/30295174/what-is-the-performance-of-stdbitset
- https://softwareengineering.stackexchange.com/questions/284160/is-there-any-advantage-to-c-style-bit-manipulation-over-stdbitset
В целом, это вопрос предпочтения, если хочется трактовать этот набор битовых флагов именно как std::bitset, можно его приводить к нему, и сравнивать каждый бит if-ами отдельно.

**Comment by QApplication** [comment]
так правильно будет работать:
```cpp
    unsigned int flags = 25;    // from field "flags"
    auto b = std::bitset<16>(flags);
    for (std::size_t i = 0; i < b.size(); ++i) {
        std::cout << "b[" << i << "]: " << b[i] << '\n';
    }
```
и результат 
```cpp
b[0]: 1
b[1]: 0
b[2]: 0
b[3]: 1
b[4]: 1
b[5]: 0
b[6]: 0
b[7]: 0
b[8]: 0
b[9]: 0
b[10]: 0
b[11]: 0
b[12]: 0
b[13]: 0
b[14]: 0
b[15]: 0
```

**Comment by elelel** [comment]
Да, можно так
