### ISSUE TITLE
И кстати почему библиотека написана C++ 11

### ISSUE THREAD

**Issue by mmonk1980** [elelel/qluacpp#3]
И кстати почему библиотека написана C++ 11, он же тормозной? Если C++ лучше C то будет 2 раза быстрей, а здесь это надо.

**Comment by elelel** [comment]
Не разделяю этого мнения

**Comment by mmonk1980** [comment]
Я вас понял. Ладно буду копать библиотеку дальше, если что не понятно куда писать?

**Comment by elelel** [comment]
Так же, как писали до этого, сюда или на форум Arqa/Quik/Lua. На форуме бываю реже.
