### ISSUE TITLE
как запустить два экземпляра 

### ISSUE THREAD

**Issue by dima-gf** [elelel/qluacpp#31]
Здравствуйте. Не подскажете как можно запустить несколько экземпляров. После запуска второго экземпляра - первый (в лучшем случае) перестает получать данные. Из форума понятно - что это не так просто запустить два экземпляра. Что нужно переименовать.
Я переименовывал LUALIB_API int luaopen_gf_quik_robot1(lua_State * L), и 
luaL_openlib(L, "gf_quik_robot1", ls_lib, 0);. 
И разносил по разным папкам -  ничего не помогает.
Спасибо.

**Comment by elelel** [comment]
Обсуждение тут https://github.com/elelel/qluacpp-tutorial/issues/26
