### ISSUE TITLE
Как вызвать OnParam callback?

### ISSUE THREAD

**Issue by mmonk1980** [elelel/qluacpp#4]
Это работает нормально:

q.set_callback<qlua::callback::OnQuote>(OnQuote);

а это нет:

q.set_callback<qlua::callback::OnParam>(OnParam);

void OnParam(lua::state& l, const char* class_code, const char* sec_code) {
	qlua::extended_api q(l);
	int a = 5;
}

**Comment by mmonk1980** [comment]
Я посмотрел исходники он не реализован?

struct OnParam : public base<OnParam> {     
      static std::string name() { return "OnParam"; }    
    }; 

это OnOnQuote:

struct OnQuote : public base<OnQuote> {
      typedef OnQuote type;
      typedef void (*handler_type) (lua::state&,
                                    const char*,
                                    const char*);
      
      static std::string name() { return "OnQuote"; }
      
      static int lua_handler(lua_State* L) {
        lua::state l(L);
        auto class_code = l.get_value<const char*>(-2);
        auto sec_code = l.get_value<const char*>(-1);
        handler_(l, class_code, sec_code);
        return 0;
      }

**Comment by elelel** [comment]
Да, в том, что сейчас опубликовано OnParam нет. В ближайшее время появится (после рефакторинга библиотеки).

**Comment by mmonk1980** [comment]
Понял.

**Comment by elelel** [comment]
Сейчас можно объявить так:

```c++
void OnParam(const lua::state& l,
             ::lua::entity<::lua::type_policy<std::string>> class_code,
             ::lua::entity<::lua::type_policy<std::string>> sec_code) {
  std::cout << "OnParam: " << class_code() << " " << sec_code() << "\n";
}
LUACPP_STATIC_FUNCTION4(OnParam, OnParam, std::string, std::string)
```

... и зарегистрировать перед luaL_openlib так:
```c++
    ::lua::function::OnParam().register_in_lua(l, OnParam);
```

**Comment by mmonk1980** [comment]
Рефакторинг библиотеки прошел или еще пишется?

**Comment by mmonk1980** [comment]
Если пишется то когда она будет готова?

**Comment by elelel** [comment]
Чтобы вызывать OnParam, уже все готово.
