### ISSUE TITLE
Вы хотели переписать библиотеку!?

### ISSUE THREAD

**Issue by mmonk1980** [elelel/qluacpp#5]
Вы хотели переписать библиотеку, прошел месяц - оно переписано или нет? Например cтарая библиотека вызывает ошибку:

qlua::instrument ins;
ins = q.getSecurityInfo("SPBFUT", "RIM7");

в этой все нормально?

**Comment by elelel** [comment]
Вызов к getSecurityInfo сделан, но я его не тестировал
